const listings=[
{id:1,type:"Subject",category:"Learning",title:"A practical guide to learning a new language",description:"A structured subject covering daily practice, useful tools, and realistic milestones for independent learners.",price:"Free",badge:"Featured",icon:"✦",tone:"lavender",location:"Canada · English",time:"2h ago"},
{id:2,type:"Resource",category:"Technology",title:"Open-source tools for a small community project",description:"A curated resource subject for teams choosing free hosting, collaboration, and communication tools.",price:"Free",badge:"",icon:"⌘",tone:"mint",location:"Online · English",time:"5h ago"},
{id:3,type:"Question",category:"Business",title:"How should a small business compare service providers?",description:"Questions and criteria for making a fair comparison without relying only on brand reputation.",price:"$4.00",badge:"",icon:"?",tone:"peach",location:"Ontario · English",time:"1d ago"},
{id:4,type:"Offer",category:"Community",title:"Local workshop: practical digital safety",description:"An accessible subject and community announcement about safer everyday digital practices.",price:"Free",badge:"Featured",icon:"◌",tone:"sky",location:"Toronto · English",time:"1d ago"},
{id:5,type:"Request",category:"Technology",title:"Looking for feedback on a privacy-first app idea",description:"A focused request for constructive subject-based feedback on an early application concept.",price:"$2.00",badge:"",icon:"↗",tone:"mint",location:"Online · English",time:"2d ago"},
{id:6,type:"Subject",category:"Business",title:"Understanding fair pricing for independent services",description:"A neutral subject exploring pricing, value, transparency, and sustainable independent work.",price:"Free",badge:"",icon:"◫",tone:"peach",location:"Canada · English",time:"3d ago"}
];
const state={query:"",category:"all",type:"all"};
const grid=document.getElementById("listingGrid"),meta=document.getElementById("resultMeta"),modal=document.getElementById("modalBackdrop"),modalContent=document.getElementById("modalContent");
function render(){const q=state.query.toLowerCase();const found=listings.filter(x=>(state.category==="all"||x.category===state.category)&&(state.type==="all"||x.type===state.type)&&(!q||[x.title,x.description,x.category,x.type].join(" ").toLowerCase().includes(q)));meta.textContent=`${found.length} active listing${found.length===1?"":"s"} · Subjects are shown without contributor identity`;grid.innerHTML=found.length?found.map(card).join(""):`<div class="empty"><h3>No listings found</h3><p>Try another subject or clear the filters.</p></div>`;}
function card(x){return `<article class="listing-card" data-id="${x.id}"><div class="listing-image ${x.tone}">${x.icon}</div><div class="listing-body"><div class="listing-tags"><span class="tag ${x.badge?"featured":""}">${x.badge||x.type}</span><span>${x.category}</span></div><h3>${x.title}</h3><p>${x.description}</p><div class="listing-footer"><span>${x.location}</span><span class="listing-price">${x.price}</span></div></div></article>`;}
function open(content){modalContent.innerHTML=content;modal.hidden=false}function close(){modal.hidden=true}
function login(){open(`<p class="eyebrow">Contributor access</p><h2>Login to continue</h2><p>Visitors can browse freely. Login is needed only to publish and manage your own listings.</p><form class="modal-form" onsubmit="event.preventDefault(); alert('Demo login accepted.'); close();"><label>Email<input type="email" placeholder="you@example.com" required></label><label>Password<input type="password" placeholder="••••••••" required></label><button class="button button-primary">Login</button></form>`);}
function post(){open(`<p class="eyebrow">New listing</p><h2>Post a subject</h2><p>Your listing will be processed by the SM workflow before publication. This demo does not send data to a server.</p><form class="modal-form" onsubmit="event.preventDefault(); alert('Demo listing saved as draft.'); close();"><label>Listing title<input placeholder="What is the subject?" required></label><label>Type<select><option>Subject</option><option>Question</option><option>Resource</option><option>Offer</option><option>Request</option></select></label><label>Category<select><option>Learning</option><option>Technology</option><option>Business</option><option>Community</option></select></label><label>Subject content<textarea placeholder="Describe the subject clearly..." required></textarea></label><div class="plan-options"><button type="button" class="plan selected"><strong>Free post</strong><small>Standard visibility · 7 days</small></button><button type="button" class="plan"><strong>Featured · $4</strong><small>Priority placement · 14 days</small></button></div><button class="button button-primary">Continue to review</button></form>`);}
function detail(id){const x=listings.find(y=>y.id===Number(id));if(!x)return;open(`<p class="eyebrow">${x.category} · ${x.type}</p><h2>${x.title}</h2><p>${x.description}</p><div class="admin-tile"><strong>Subject-only publication</strong><small>Public contributor identity and history are not displayed.</small></div><div class="listing-footer" style="margin-top:22px"><span>${x.location} · Published ${x.time}</span><strong>${x.price}</strong></div><div style="display:flex;gap:10px;margin-top:24px"><button class="button button-primary" data-action="contact">Contact through relay</button><button class="button button-ghost" data-action="report">Report listing</button></div>`);}
function admin(){open(`<p class="eyebrow">Control plane</p><h2>Marketplace administration</h2><p>Configuration is private and role-controlled. This is the first interface preview.</p><div class="admin-grid"><div class="admin-tile"><strong>Categories</strong><small>4 active · 12 subcategories</small></div><div class="admin-tile"><strong>Moderation queue</strong><small>8 awaiting review</small></div><div class="admin-tile"><strong>Roles & permissions</strong><small>5 roles configured</small></div><div class="admin-tile"><strong>Posting policies</strong><small>Free and paid plans</small></div><div class="admin-tile"><strong>Advertisements</strong><small>Campaign management</small></div><div class="admin-tile"><strong>Audit logs</strong><small>Private administrative record</small></div></div>`);}
document.addEventListener("click",e=>{const action=e.target.closest("[data-action]")?.dataset.action;if(action==="login")login();if(action==="post")post();if(action==="admin")admin();if(action==="close")close();if(action==="home"){e.preventDefault();scrollTo({top:0,behavior:"smooth"})}if(action==="contact")alert("Demo relay opened.");if(action==="report")alert("Demo report form opened.");const c=e.target.closest("[data-category]")?.dataset.category;if(c){state.category=c;document.getElementById("categoryFilter").value=c;document.getElementById("browse").scrollIntoView({behavior:"smooth"});render()}const plan=e.target.closest(".plan");if(plan){document.querySelectorAll(".plan").forEach(x=>x.classList.remove("selected"));plan.classList.add("selected")}const item=e.target.closest(".listing-card");if(item)detail(item.dataset.id);});
document.getElementById("searchInput").addEventListener("input",e=>{state.query=e.target.value;render()});document.getElementById("categoryFilter").addEventListener("change",e=>{state.category=e.target.value;render()});document.getElementById("typeFilter").addEventListener("change",e=>{state.type=e.target.value;render()});document.getElementById("clearFilters").addEventListener("click",()=>{state.query="";state.category="all";state.type="all";document.getElementById("searchInput").value="";document.getElementById("categoryFilter").value="all";document.getElementById("typeFilter").value="all";render()});document.getElementById("modalBackdrop").addEventListener("click",e=>{if(e.target===modal)close()});render();