const state={query:"",category:"all",type:"all",user:null};
const grid=document.getElementById("listingGrid"),meta=document.getElementById("resultMeta"),modal=document.getElementById("modalBackdrop"),modalContent=document.getElementById("modalContent");
const fallback=[{id:1,type:"Subject",category:"Learning",title:"A practical guide to learning a new language",description:"A structured subject covering daily practice, useful tools, and realistic milestones for independent learners.",price:"Free",plan:"featured",location:"Canada",language:"English"},{id:2,type:"Resource",category:"Technology",title:"Open-source tools for a small community project",description:"A curated resource subject for teams choosing free hosting, collaboration, and communication tools.",price:"Free",plan:"free",location:"Online",language:"English"}];
const esc=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const tone=x=>({Learning:"lavender",Technology:"mint",Business:"peach",Community:"sky"}[x]||"mint");
const icon=x=>({Learning:"✦",Technology:"⌘",Business:"◫",Community:"◌"}[x]||"◎");
async function api(url,options={}){const r=await fetch(url,{credentials:"same-origin",headers:{"content-type":"application/json",...(options.headers||{})},...options});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||"Request failed");return data}
async function refresh(){const params=new URLSearchParams({q:state.query,category:state.category,type:state.type});try{const data=await api("/api/listings?"+params);render(data.listings)}catch{render(fallback)}}
function render(items){meta.textContent=`${items.length} active listing${items.length===1?"":"s"} · Subjects are shown without contributor identity`;grid.innerHTML=items.length?items.map(card).join(""):`<div class="empty"><h3>No listings found</h3><p>Try another subject or clear the filters.</p></div>`}
function card(x){return `<article class="listing-card" data-id="${x.id}"><div class="listing-image ${tone(x.category)}">${icon(x.category)}</div><div class="listing-body"><div class="listing-tags"><span class="tag ${x.plan==="featured"?"featured":""}">${x.plan==="featured"?"Featured":esc(x.type)}</span><span>${esc(x.category)}</span></div><h3>${esc(x.title)}</h3><p>${esc(x.description)}</p><div class="listing-footer"><span>${esc(x.location)} · ${esc(x.language)}</span><span class="listing-price">${esc(x.price||"Free")}</span></div></div></article>`}
function open(content){modalContent.innerHTML=content;modal.hidden=false}function close(){modal.hidden=true}
async function currentUser(){if(state.user)return state.user;const data=await api("/api/auth/me");state.user=data.user;return state.user}
function login(){open(`<p class="eyebrow">Contributor access</p><h2>Login to continue</h2><p>Visitors can browse freely. Login is needed only to publish and manage your own listings.</p><form id="authForm" class="modal-form"><label>Email<input name="email" type="email" placeholder="you@example.com" required></label><label>Password<input name="password" type="password" placeholder="At least 8 characters" required></label><button class="button button-primary">Login</button><button type="button" class="button button-ghost" data-action="register">Create an account</button><p id="formError" class="form-error"></p></form>`);document.getElementById("authForm").addEventListener("submit",submitLogin)}
function register(){open(`<p class="eyebrow">Create contributor account</p><h2>Join Subject Matter</h2><p>Your public listings do not display your identity or account history.</p><form id="authForm" class="modal-form"><label>Display name<input name="displayName" placeholder="Private account label"></label><label>Email<input name="email" type="email" placeholder="you@example.com" required></label><label>Password<input name="password" type="password" placeholder="At least 8 characters" minlength="8" required></label><button class="button button-primary">Create account</button><button type="button" class="button button-ghost" data-action="login">Back to login</button><p id="formError" class="form-error"></p></form>`);document.getElementById("authForm").addEventListener("submit",submitRegister)}
async function submitLogin(e){e.preventDefault();try{const data=await api("/api/auth/login",{method:"POST",body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});state.user=data.user;close();updateAuth()}catch(error){document.getElementById("formError").textContent=error.message}}
async function submitRegister(e){e.preventDefault();try{const data=await api("/api/auth/register",{method:"POST",body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});state.user=data.user;close();updateAuth()}catch(error){document.getElementById("formError").textContent=error.message}}
async function post(){try{if(!await currentUser())return login();}catch{return login()}open(`<p class="eyebrow">New listing</p><h2>Post a subject</h2><p>The listing is saved as a private draft until the moderation and publication workflow is completed.</p><form id="listingForm" class="modal-form"><label>Listing title<input name="title" placeholder="What is the subject?" required minlength="5"></label><label>Type<select name="type"><option>Subject</option><option>Question</option><option>Resource</option><option>Offer</option><option>Request</option></select></label><label>Category<select name="category"><option>Learning</option><option>Technology</option><option>Business</option><option>Community</option></select></label><label>Subject content<textarea name="description" placeholder="Describe the subject clearly..." required minlength="20"></textarea></label><label>Location<input name="location" value="Online"></label><label>Language<select name="language"><option>English</option><option>French</option><option>Farsi</option><option>Turkish</option></select></label><div class="plan-options"><button type="button" class="plan selected" data-plan="free"><strong>Free post</strong><small>Standard visibility · 7 days</small></button><button type="button" class="plan" data-plan="featured"><strong>Featured · $4</strong><small>Priority placement · 14 days</small></button></div><input type="hidden" name="plan" value="free"><button class="button button-primary">Save draft</button><p id="formError" class="form-error"></p></form>`);document.getElementById("listingForm").addEventListener("submit",submitListing)}
async function submitListing(e){e.preventDefault();const form=e.target;try{await api("/api/my/listings",{method:"POST",body:JSON.stringify(Object.fromEntries(new FormData(form)))});close();alert("Listing saved as a private draft.");}catch(error){document.getElementById("formError").textContent=error.message}}
async function account(){try{const user=await currentUser();const data=await api("/api/my/listings");open(`<p class="eyebrow">Private contributor area</p><h2>My listings</h2><p>Only you can see this management view. Public visitors cannot search your history.</p><div class="admin-grid">${data.listings.length?data.listings.map(x=>`<div class="admin-tile"><strong>${esc(x.title)}</strong><small>${esc(x.status)} · ${esc(x.plan)} · ${esc(x.category)}</small><button class="button button-ghost" data-delete="${x.id}">Remove</button></div>`).join(""):"<div class=\"admin-tile\"><strong>No listings yet</strong><small>Create your first subject listing.</small></div>"}</div><div style="display:flex;gap:10px;margin-top:22px"><button class="button button-primary" data-action="post">Post a listing</button><button class="button button-ghost" data-action="logout">Log out</button></div>`)}catch{login()}}
function detail(id){api("/api/listings").then(data=>{const x=data.listings.find(y=>y.id===Number(id));if(!x)return;open(`<p class="eyebrow">${esc(x.category)} · ${esc(x.type)}</p><h2>${esc(x.title)}</h2><p>${esc(x.description)}</p><div class="admin-tile"><strong>Subject-only publication</strong><small>Public contributor identity and history are not displayed.</small></div><div class="listing-footer" style="margin-top:22px"><span>${esc(x.location)} · ${esc(x.language)}</span><strong>${esc(x.price)}</strong></div><div style="display:flex;gap:10px;margin-top:24px"><button class="button button-primary" data-action="contact">Contact through relay</button><button class="button button-ghost" data-action="report">Report listing</button></div>`)})}
function admin(){open(`<p class="eyebrow">Control plane preview</p><h2>Marketplace administration</h2><p>Configuration is private and role-controlled. The production admin portal will use the same permission boundaries.</p><div class="admin-grid"><div class="admin-tile"><strong>Categories</strong><small>4 active · 12 subcategories</small></div><div class="admin-tile"><strong>Moderation queue</strong><small>8 awaiting review</small></div><div class="admin-tile"><strong>Roles & permissions</strong><small>5 roles configured</small></div><div class="admin-tile"><strong>Posting policies</strong><small>Free and paid plans</small></div><div class="admin-tile"><strong>Advertisements</strong><small>Campaign management</small></div><div class="admin-tile"><strong>Audit logs</strong><small>Private administrative record</small></div></div>`)}
function updateAuth(){const b=document.querySelector('[data-action="login"]');if(b){b.textContent=state.user?"Account":"Log in";b.dataset.action=state.user?"account":"login"}}
document.addEventListener("click",async e=>{const action=e.target.closest("[data-action]")?.dataset.action;if(action==="login")login();if(action==="register")register();if(action==="post")post();if(action==="admin")admin();if(action==="account")account();if(action==="logout"){await api("/api/auth/logout",{method:"POST"});state.user=null;close();updateAuth()}if(action==="close")close();if(action==="home"){e.preventDefault();scrollTo({top:0,behavior:"smooth"})}if(action==="contact")alert("Demo relay opened.");if(action==="report")alert("Demo report form opened.");const c=e.target.closest("[data-category]")?.dataset.category;if(c){state.category=c;document.getElementById("categoryFilter").value=c;document.getElementById("browse").scrollIntoView({behavior:"smooth"});refresh()}const plan=e.target.closest(".plan");if(plan){document.querySelectorAll(".plan").forEach(x=>x.classList.remove("selected"));plan.classList.add("selected");const input=document.querySelector('input[name="plan"]');if(input)input.value=plan.dataset.plan}const remove=e.target.closest("[data-delete]");if(remove&&confirm("Remove this listing?")){await api("/api/my/listings/"+remove.dataset.delete,{method:"DELETE"});account()}const item=e.target.closest(".listing-card");if(item)detail(item.dataset.id)});
document.getElementById("searchInput").addEventListener("input",e=>{state.query=e.target.value;refresh()});document.getElementById("categoryFilter").addEventListener("change",e=>{state.category=e.target.value;refresh()});document.getElementById("typeFilter").addEventListener("change",e=>{state.type=e.target.value;refresh()});document.getElementById("clearFilters").addEventListener("click",()=>{state.query="";state.category="all";state.type="all";document.getElementById("searchInput").value="";document.getElementById("categoryFilter").value="all";document.getElementById("typeFilter").value="all";refresh()});document.getElementById("modalBackdrop").addEventListener("click",e=>{if(e.target===modal)close()});
currentUser().then(()=>updateAuth()).catch(()=>{});refresh();